#!/usr/bin/env sh

uglifycss src/root.css --output css/root.min.css
uglifycss src/typography.css --output css/typography.min.css

for f in css/root.min.css css/typography.min.css; do
	cat "$f"
	echo
done > dist/cdpi.min.css

uglifycss src/calendar/calendar.css --output css/calendar.min.css
uglifycss src/calendar/date.css --output css/date.min.css

for f in css/calendar.min.css css/date.min.css; do
	cat "$f"
	echo
done > dist/calendar.min.css

########################################################################################################################################

uglifycss src/themes/minimalist/colors.css --output css/minimalist-colors.min.css
uglifycss src/themes/minimalist/calendar.css --output css/minimalist-calendar.min.css
uglifycss src/themes/minimalist/tag.css --output css/minimalist-tag.min.css

for f in css/minimalist-colors.min.css css/minimalist-calendar.min.css css/minimalist-tag.min.css; do
	cat "$f"
	echo
done > dist/minimalist.min.css

########################################################################################################################################

#cat dist/monk.min.css dist/calendar.min.css dist/minimalist.min.css > dist/monk-full.min.css

#for f in dist/root.min.css dist/calendar.min.css; do
#	cat "$f"
#	echo
#done > dist/dsjfkdhfjksdhfjdfsdkjfhdkjs.min.css
